AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for DevOps Project Backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  DevOpsBackend:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 256
      Events:
        ApiEvent:
          Type: HttpApi
      Tracing: Active
      Environment:
        Variables:
          FLASK_ENV: production
          DB_USER: '{{resolve:secretsmanager:arn:aws:secretsmanager:eu-north-1:590183991179:secret:MongoDB-kN1EPK:SecretString:Username}}'
          DB_PASS: '{{resolve:secretsmanager:arn:aws:secretsmanager:eu-north-1:590183991179:secret:MongoDB-kN1EPK:SecretString:Password}}'
          ENCRYPT_KEY: '{{resolve:secretsmanager:arn:aws:secretsmanager:eu-north-1:590183991179:secret:FernetEncryptionKey-BcYV5A:SecretString:EncryptionKey}}'

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: devops-backend

Outputs:
  FlaskApi:
    Description: "API Gateway endpoint URL for Prod stage for Flask function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
  DevOpsBackend:
    Description: "Flask Lambda Function ARN"
    Value: !GetAtt DevOpsBackend.Arn
  FlaskIamRole:
    Description: "Implicit IAM Role created for Flask function"
    Value: !GetAtt DevOpsBackendRole.Arn